import type { ItemOption } from '../types';

export const items: ItemOption[] = [
  // ============== 灵石 ==============
  {
    id: 'stone-100',
    name: '下品灵石 · 一袋',
    subtitle: '约 100 枚',
    desc: '修行人的零钱，散市上够买几瓶玉露酒。',
    cost: 1,
    category: '灵石',
    灵石: 100,
    glyph: '石',
  },
  {
    id: 'stone-1000',
    name: '中品灵石 · 一囊',
    subtitle: '约 1000 枚',
    desc: '足以采购下境功法残页或一柄黄品法器。',
    cost: 4,
    category: '灵石',
    灵石: 1000,
    glyph: '石',
  },
  {
    id: 'stone-10000',
    name: '一笔修行经费',
    subtitle: '约 10000 枚',
    desc: '令小宗门一年开支无忧。',
    cost: 10,
    category: '灵石',
    灵石: 10000,
    glyph: '石',
    tags: ['豪富'],
  },

  // ============== 功法 ==============
  {
    id: 'art-yinqi',
    name: '凡息引气诀',
    subtitle: '凡品 · 心法',
    desc: '最初级的引气入体心法，凡人也能修练。',
    cost: 1,
    category: '功法',
    glyph: '心',
    data: {
      品质: '凡',
      境界: '凡人',
      类型: '心法',
      标签: ['基础', '入门'],
      使用中: false,
    },
  },
  {
    id: 'art-xuanshuang',
    name: '玄霜剑诀',
    subtitle: '玄品 · 心法',
    desc: '剑宗筑基弟子常修的心法之一，运转时周身有冰冷剑意。',
    cost: 5,
    category: '功法',
    glyph: '心',
    data: {
      品质: '玄',
      境界: '炼气',
      五行: '水',
      类型: '心法',
      消耗: '灵力-1/时辰',
      标签: ['宗门', '剑修', '寒系'],
      效果: { 剑意凝聚: '施法时附带寒霜效果' },
      使用中: false,
    },
  },
  {
    id: 'art-tielou',
    name: '玄龟铁布衫',
    subtitle: '黄品 · 护体',
    desc: '外门弟子常修的硬功，运功时皮肤微泛玄色光泽。',
    cost: 3,
    category: '功法',
    glyph: '护',
    data: {
      品质: '黄',
      境界: '炼气',
      五行: '土',
      类型: '护体',
      消耗: '灵力-2/时辰',
      标签: ['防御', '炼体'],
      效果: { 肉身坚韧: '防御+5' },
      使用中: false,
    },
  },
  {
    id: 'art-yufeng',
    name: '御风踏雪步',
    subtitle: '黄品 · 身法',
    desc: '杂役弟子也能修练的轻身术，可以在雪地上略微提速。',
    cost: 2,
    category: '功法',
    glyph: '身',
    data: {
      品质: '黄',
      境界: '炼气',
      五行: '金',
      类型: '身法',
      标签: ['基础'],
      使用中: false,
    },
  },
  {
    id: 'art-duanyue',
    name: '断岳一式',
    subtitle: '玄品 · 攻击',
    desc: '施展时灵力凝于剑尖，斩出后犹如山岳崩落。',
    cost: 5,
    category: '功法',
    glyph: '攻',
    data: {
      品质: '玄',
      境界: '炼气',
      五行: '金',
      类型: '攻击',
      消耗: '灵力-5/式',
      标签: ['剑诀'],
      效果: { 破障: '对岩石类目标伤害+50%' },
      使用中: false,
    },
  },

  // ============== 装备 ==============
  {
    id: 'eq-shortsword',
    name: '寒铁短剑',
    subtitle: '凡品 · 法宝',
    desc: '杂役院发放的练手短剑，简陋而锋利。',
    cost: 1,
    category: '装备',
    glyph: '剑',
    data: {
      品质: '凡',
      境界: '凡人',
      类型: '法宝',
      五行: '金',
      标签: ['武器', '入门'],
      攻击力: 5,
      效果: { 破甲: '穿透轻甲' },
      位置: '手部',
    },
  },
  {
    id: 'eq-daopao',
    name: '粗布道袍',
    subtitle: '凡品 · 护甲',
    desc: '杂役弟子统一发放的青色道袍。',
    cost: 1,
    category: '装备',
    glyph: '袍',
    data: {
      品质: '凡',
      类型: '护甲',
      标签: ['日常'],
      防御力: 2,
      位置: '上装',
    },
  },
  {
    id: 'eq-bag',
    name: '储物锦囊·小',
    subtitle: '黄品 · 工具',
    desc: '小型储物法器，日常随身。可额外容纳 10 件低阶物品。',
    cost: 2,
    category: '装备',
    glyph: '囊',
    data: {
      品质: '黄',
      类型: '工具',
      标签: ['收纳'],
      效果: { 容量: '额外容纳10件低阶物品' },
      位置: '腰间',
    },
  },
  {
    id: 'eq-yujian',
    name: '雪魄飞剑',
    subtitle: '玄品 · 法宝',
    desc: '杂役院档案中提到的失物，于雪洞偶得。锋刃如冬月寒辉。',
    cost: 7,
    category: '装备',
    glyph: '剑',
    data: {
      品质: '玄',
      境界: '筑基',
      类型: '法宝',
      五行: '水',
      消耗: '灵力-2/次',
      标签: ['飞剑', '寒系'],
      攻击力: 22,
      效果: { 御剑: '可御剑短距离飞行', 寒霜: '命中附加寒气入体' },
      位置: '储物袋',
    },
    tags: ['稀有'],
  },

  // ============== 物品 ==============
  {
    id: 'item-ningqi',
    name: '凝气丹 · 十枚',
    subtitle: '凡品 · 丹药',
    desc: '修真界最常见的入门丹药，凡人也可服用以助引气。',
    cost: 1,
    category: '物品',
    glyph: '丹',
    data: {
      品质: '凡',
      境界: '凡人',
      类型: '丹药',
      消耗: '1颗',
      标签: ['修炼'],
      数量: 10,
      效果: { 修为: '服用立即获得修为+5' },
    },
  },
  {
    id: 'item-huanxue',
    name: '还血膏 · 三盒',
    subtitle: '黄品 · 丹药',
    desc: '炼气期修士常备的疗伤丹药，色泽暗红如凝血。',
    cost: 2,
    category: '物品',
    glyph: '丹',
    data: {
      品质: '黄',
      境界: '炼气',
      类型: '丹药',
      五行: '火',
      消耗: '1盒',
      标签: ['疗伤'],
      数量: 3,
      效果: { 疗伤: '立即恢复气血15点', 止血: '外伤止血' },
    },
  },
  {
    id: 'item-fulu',
    name: '清霜符 · 五张',
    subtitle: '凡品 · 符箓',
    desc: '杂役弟子日常防寒所用，效果有限。',
    cost: 1,
    category: '物品',
    glyph: '符',
    data: {
      品质: '凡',
      类型: '符箓',
      五行: '水',
      消耗: '1张',
      标签: ['防御'],
      数量: 5,
      效果: { 护体: '施加6时辰御寒护盾' },
    },
  },
  {
    id: 'item-yinlei',
    name: '引雷符',
    subtitle: '玄品 · 符箓',
    desc: '颇为珍贵的攻击型符箓，珍藏未用。',
    cost: 4,
    category: '物品',
    glyph: '符',
    data: {
      品质: '玄',
      类型: '符箓',
      五行: '火',
      消耗: '1张',
      标签: ['攻击'],
      数量: 1,
      效果: { 雷击: '造成范围雷电伤害' },
    },
  },
];

export const findItem = (id: string) => items.find(it => it.id === id);

export const itemsByCategory = (cat: ItemOption['category']) =>
  items.filter(it => it.category === cat);
