import type { PhysiqueOption } from '../types';

export const physiques: PhysiqueOption[] = [
  {
    id: 'phy-fan',
    name: '寻常凡体',
    subtitle: '凡夫之躯',
    desc: '与天地无异，无奇也无短；最易得见，亦最难超脱。',
    cost: 0,
    悟性: 8,
    根骨: 8,
    气感: 8,
    glyph: '凡',
    tags: ['免费'],
  },
  {
    id: 'phy-ling',
    name: '微灵之体',
    subtitle: '稍具异象',
    desc: '气感胜于常人，修行起步顺遂。',
    cost: 3,
    悟性: 11,
    根骨: 9,
    气感: 12,
    效果: { 引气速度: '+10%' },
    glyph: '灵',
  },
  {
    id: 'phy-bone',
    name: '玄铁筋骨',
    subtitle: '体魄如山',
    desc: '骨骼坚韧，痛楚迟钝；炼体功法事半功倍。',
    cost: 4,
    悟性: 8,
    根骨: 16,
    气感: 7,
    效果: { 防御: '+5', 物理伤害减免: '10%' },
    glyph: '骨',
  },
  {
    id: 'phy-mind',
    name: '通玄道体',
    subtitle: '聪慧绝伦',
    desc: '一闻三悟，参悟功法常生奇思。',
    cost: 6,
    悟性: 18,
    根骨: 8,
    气感: 11,
    效果: { 参悟加成: '+20%', 神识感知: '+15%' },
    glyph: '玄',
  },
  {
    id: 'phy-jian',
    name: '剑骨之躯',
    subtitle: '为剑而生',
    desc: '与剑器同频，闻锋铁声便心潮澎湃。',
    cost: 7,
    悟性: 12,
    根骨: 13,
    气感: 13,
    效果: { 御剑加成: '+25%', 剑系功法领悟: '+20%' },
    glyph: '剑',
    tags: ['稀有'],
  },
  {
    id: 'phy-immortal',
    name: '太初仙体',
    subtitle: '夺天地造化',
    desc: '生而契道，三日小成，七日大成；万古难求。',
    cost: 14,
    悟性: 20,
    根骨: 18,
    气感: 19,
    效果: { 修为获取: '+30%', 寿元: '+200', 状态抗性: '+25%' },
    glyph: '仙',
    tags: ['传说'],
  },
];

export const findPhysique = (id: string | null) =>
  physiques.find(p => p.id === id);
