import type { RootOption } from '../types';

export const roots: RootOption[] = [
  {
    id: 'root-fan',
    name: '凡品灵根',
    subtitle: '资质平平',
    desc: '与灵气相隔甚远，唯以勤勉补之。',
    cost: 0,
    品阶: '无灵根',
    五行: ['无'],
    glyph: '凡',
    tags: ['免费'],
  },
  {
    id: 'root-jin-single',
    name: '金灵根',
    subtitle: '锋锐利落',
    desc: '与金属相亲，剑修首选；攻击犀利。',
    cost: 4,
    品阶: '单灵根',
    五行: ['金'],
    glyph: '金',
  },
  {
    id: 'root-shui-single',
    name: '水灵根',
    subtitle: '柔中带韧',
    desc: '与水相亲，丹师与符修青睐；恢复迅捷。',
    cost: 4,
    品阶: '单灵根',
    五行: ['水'],
    glyph: '水',
  },
  {
    id: 'root-mu-single',
    name: '木灵根',
    subtitle: '生发不息',
    desc: '与木相亲，灵植/医道之路坦途。',
    cost: 4,
    品阶: '单灵根',
    五行: ['木'],
    glyph: '木',
  },
  {
    id: 'root-huo-single',
    name: '火灵根',
    subtitle: '烈焰焚天',
    desc: '与火相亲，炼器/炼丹效率倍增；攻势暴烈。',
    cost: 4,
    品阶: '单灵根',
    五行: ['火'],
    glyph: '火',
  },
  {
    id: 'root-tu-single',
    name: '土灵根',
    subtitle: '厚德载物',
    desc: '与土相亲，体魄稳健，护体功法事半功倍。',
    cost: 4,
    品阶: '单灵根',
    五行: ['土'],
    glyph: '土',
  },
  {
    id: 'root-jin-shui',
    name: '金水双灵根',
    subtitle: '剑符双修',
    desc: '锋锐与柔润并行，剑修兼修符箓。',
    cost: 6,
    品阶: '双灵根',
    五行: ['金', '水'],
    glyph: '双',
  },
  {
    id: 'root-mu-huo',
    name: '木火双灵根',
    subtitle: '丹道之资',
    desc: '生发与焰煅相得益彰，最适炼丹。',
    cost: 6,
    品阶: '双灵根',
    五行: ['木', '火'],
    glyph: '双',
  },
  {
    id: 'root-yin-yang',
    name: '阴阳双灵根',
    subtitle: '极端造化',
    desc: '阴阳相济，神鬼莫测；幻术、心法皆有奇效。',
    cost: 10,
    品阶: '双灵根',
    五行: ['阴', '阳'],
    glyph: '极',
    tags: ['稀有'],
  },
  {
    id: 'root-hundun',
    name: '混沌灵根',
    subtitle: '万法俱全',
    desc: '十方俱通，悟性极佳；亘古难得一遇。',
    cost: 16,
    品阶: '上品灵根',
    五行: ['混沌'],
    glyph: '混',
    tags: ['传说'],
  },
];

export const findRoot = (id: string | null) => roots.find(r => r.id === id);
