import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const vue = require('vue');
const sfc = require('vue/compiler-sfc');
const ts = require('typescript');
const filename = 'src/修仙状态栏/pages/PageMap.vue';
const { descriptor, errors } = sfc.parse(fs.readFileSync(filename, 'utf8'), { filename });
assert.equal(errors.length, 0);
const script = sfc.compileScript(descriptor, { id: 'earth-map-test' });
assert.deepEqual(sfc.compileTemplate({ source: descriptor.template.content, filename, id: 'earth-map-test', compilerOptions: { bindingMetadata: script.bindings } }).errors, []);
const js = ts.transpileModule(script.content, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const store = vue.reactive({ data: { 地点: { 世界: '地球', 地域: '中国' } } });
const module = { exports: {} };
const localRequire = id => id === 'vue' ? vue : id === '../store' ? { useDataStore: () => store } : id === '../composables' ? { openLightbox() {} } : { default: id };
vm.runInNewContext('(function(require,module,exports){' + js + '\n})', { window: {} })(localRequire, module, module.exports);
const state = module.exports.default.setup({}, { expose() {} });
let checks = 2;
for (const region of ['中国', '日本', '俄罗斯', '欧盟', '英美', '以色列', '中东', '印度', '非洲', '']) {
  store.data.地点.地域 = region;
  await vue.nextTick();
  assert.equal(state.selected.地域, '全图');
  assert.equal(state.mapTitle.value, '地球全图');
  assert.match(state.currentMap.value, /地球地图/);
  assert.deepEqual(Array.from(state.tree.value.find(w => w.name === '地球').regions), ['全图']);
  assert(state.isHere('地球', '全图'));
  checks += 5;
}
store.data.地点 = { 世界: '灵界', 地域: '陨落大陆' };
await vue.nextTick();
assert.equal(state.selected.地域, '殒落大陆');
assert.match(state.currentMap.value, /殒落大陆地图/);
state.selectRegion('地球', '全图');
store.data.地点.地域 = '太初大陆';
await vue.nextTick();
assert.equal(state.selected.世界, '地球');
assert.match(state.currentMap.value, /地球地图/);
checks += 4;
assert(fs.statSync('dist/修仙状态栏/index.html').size < 20 * 1024 * 1024);
assert(fs.readFileSync('dist/修仙状态栏/index.html', 'utf8').includes('data:image/png;base64,'));
console.log(`${checks + 2} Earth map checks passed.`);
